# Generated by Django 2.1.5 on 2019-10-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('BL_number', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('released', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('initiation_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('contract_amount_mt', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('proforma_number', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('l', 'Lead'), ('cr', 'Compliance review'), ('n', 'Negotiation'), ('p', 'Pro-Format'), ('s', 'Signed'), ('c', 'Completed'), ('cl', 'Cancelled'), ('d', 'Default'), ('pc', 'Partially completed'), ('a', 'Assignment')], default='I', help_text='Current Status', max_length=2)),
                ('effective_incoterm', models.CharField(blank=True, choices=[('cfr', 'CFR'), ('dap', 'DAP'), ('dat', 'DAT'), ('fob', 'FOB')], max_length=3, null=True)),
                ('delivery_port', models.CharField(choices=[('a', 'Amirabad'), ('afz', 'Anzali Free Zone'), ('s', 'Southern Ports'), ('n', 'Northern Ports'), ('d', 'Default'), ('t', 'TBD')], default='afz', max_length=3)),
                ('payment_conditions', models.CharField(blank=True, choices=[('l', 'L/C'), ('t', 'T.T.'), ('b', 'L/C or T.T.')], max_length=2, null=True)),
                ('payment_status', models.CharField(choices=[('n', 'Not paid'), ('p', 'Partial payment'), ('f', 'Full payment'), ('g', 'Payment agreement'), ('d', 'Default')], default='d', max_length=1)),
                ('compliance_review', models.CharField(choices=[('n', 'NEGATIVE - NO PB'), ('p', 'POSITIVE - HIT'), ('na', 'N.A.'), ('nc', 'Not Checked')], default='na', max_length=2)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(help_text='Which currency', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('commercial_id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=14, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=14, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=14, null=True)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('ceo', models.CharField(blank=True, max_length=60, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('customs_clearance_number', models.IntegerField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('tank_in', 'IN'), ('tank_out', 'OUT')], max_length=8)),
                ('amount_metric_ton', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('billoflading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.BillOfLading')),
                ('contract_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('customs_clearance_number', models.IntegerField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('tank_in', 'IN'), ('tank_out', 'OUT')], max_length=8)),
                ('amount_mt', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('amount_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('billoflading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.BillOfLading')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=14, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('rate_1_usd', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Currency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('trip_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('vessel_name', models.CharField(blank=True, choices=[('g', 'Geroii Rosii Pyatnitskyh'), ('a', 'Azeri Karabakh'), ('m', 'Marshal Tukhachevskiy'), ('d', 'Dahi ByulByul'), ('n', 'Neatis')], max_length=1, null=True)),
                ('vessel_status', models.CharField(blank=True, choices=[('ast_amr', 'Sails Astrakhan to Amirabad'), ('ast_afz', 'Sails Astrakhan to Anzali Free Zone'), ('c', 'TRIP COMPLETED')], max_length=8, null=True)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('tank_in', 'IN'), ('tank_out', 'OUT')], max_length=8)),
                ('amount_metric_ton', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('amount_cubic_meter', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('number_of_BL', models.IntegerField()),
                ('contract_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('capacity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shipping',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Storage'),
        ),
        migrations.AddField(
            model_name='operation',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Shipping'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Shipping'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Storage'),
        ),
        migrations.AddField(
            model_name='contract',
            name='consignee',
            field=models.ManyToManyField(blank=True, related_name='Customer', to='prjmgr.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Currency'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer'),
        ),
        migrations.AddField(
            model_name='billoflading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract'),
        ),
        migrations.AddField(
            model_name='billoflading',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer'),
        ),
        migrations.AddField(
            model_name='billoflading',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Shipping'),
        ),
    ]
