# Generated by Django 2.1.5 on 2019-10-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
