# Generated by Django 2.2.1 on 2019-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='consignee',
        ),
        migrations.AddField(
            model_name='contract',
            name='consignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='Customer', to='prjmgr.Customer'),
        ),
    ]
