# Generated by Django 2.2.1 on 2019-09-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0002_auto_20190924_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee', to='prjmgr.Customer'),
        ),
    ]
