# Generated by Django 2.2.1 on 2019-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0002_payment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
