# Generated by Django 2.2.1 on 2019-09-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0003_auto_20190921_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_amount',
            new_name='contract_amount_mt',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='delivery_completion_date',
        ),
    ]
