# Generated by Django 2.2.1 on 2019-09-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0004_auto_20190924_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='consignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='prjmgr.Customer'),
        ),
    ]
