# Generated by Django 2.2.1 on 2019-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0008_auto_20190924_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
