# Generated by Django 2.2.1 on 2019-09-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0009_payment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
