# Generated by Django 2.2.1 on 2019-09-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0010_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
