# Generated by Django 2.1.5 on 2019-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0012_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('tank_in', 'IN'), ('tank_out', 'OUT')], max_length=2),
        ),
    ]
