# Generated by Django 2.1.5 on 2019-10-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0015_auto_20191004_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='contract_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
