# Generated by Django 2.1.5 on 2019-10-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0016_auto_20191008_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivered_amount',
            new_name='amount_metric_ton',
        ),
    ]
