# Generated by Django 2.1.5 on 2019-10-08 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0017_auto_20191008_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='operation_type',
            field=models.CharField(choices=[('tank_in', 'IN'), ('tank_out', 'OUT')], default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='billoflading',
            field=models.ManyToManyField(blank=True, null=True, to='prjmgr.BillOfLading'),
        ),
        migrations.AddField(
            model_name='operation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract'),
        ),
        migrations.AddField(
            model_name='operation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer'),
        ),
        migrations.AddField(
            model_name='operation',
            name='customs_clearance_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Shipping'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='operation_type',
            field=models.CharField(choices=[('tank_in', 'IN'), ('tank_out', 'OUT')], default='tank_in', max_length=8),
            preserve_default=False,
        ),
    ]
