# Generated by Django 2.1.5 on 2019-10-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0018_auto_20191008_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billoflading',
            old_name='weight',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='billoflading',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billoflading',
            name='receipnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Customer'),
        ),
        migrations.RemoveField(
            model_name='operation',
            name='billoflading',
        ),
        migrations.AddField(
            model_name='operation',
            name='billoflading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.BillOfLading'),
        ),
    ]
