# Generated by Django 2.1.5 on 2019-10-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0019_auto_20191008_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoflading',
            name='BL_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
