# Generated by Django 2.1.5 on 2019-10-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0020_auto_20191008_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='billoflading',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjmgr.Contract'),
        ),
    ]
