# Generated by Django 2.1.5 on 2019-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0021_billoflading_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billoflading',
            old_name='receipnt',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='billoflading',
            name='released',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
