# Generated by Django 2.1.5 on 2019-10-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0022_auto_20191008_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rate_1_usd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
