# Generated by Django 2.1.5 on 2019-10-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0023_auto_20191009_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='currency_type',
            new_name='currency',
        ),
    ]
