# Generated by Django 2.1.5 on 2019-10-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjmgr', '0024_auto_20191009_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='id',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='trip_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
