# Generated by Django 2.2.1 on 2019-09-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190903_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returneddd'), ('my_test', 'This is a test Permission'))},
        ),
    ]
