# Generated by Django 2.2.1 on 2019-09-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190903_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('mark_returned', 'I want to change this'), ('my_test', 'This is a test Permission'))},
        ),
    ]
