# Generated by Django 2.2.1 on 2019-09-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190903_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Show_borrowers', 'Only librarians'),)},
        ),
    ]
