# Generated by Django 2.2.1 on 2019-09-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190903_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('Show_borrowers', 'Only librarians'),)},
        ),
    ]
